branch-defaults:
  master:
    environment: real-estate-dev
    group_suffix: null
global:
  application_name: real_estate
  branch: null
  default_ec2_keyname: real-estate
  default_platform: Python 2.7
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
