branch-defaults:
  master:
    environment: real-estate-dev
    group_suffix: null
global:
  application_name: real_estate
  branch: null
  default_ec2_keyname: real-estate
  default_platform: Python 2.7
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application


option_settings:
  "aws:elasticbeanstalk:application:environment":
    DJANGO_SETTINGS_MODULE: "real_estate.settings"
  "aws:elasticbeanstalk:container:python":
    WSGIPath: real_estate/wsgi.py
    NumProcesses: 3
    NumThreads: 20
  "aws:elasticbeanstalk:container:python:staticfiles":
    "/static/": "www/static/"