# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20181107_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenitytype',
            options={'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyamenity',
            options={'verbose_name_plural': 'Property Amenities'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Property Type', 'verbose_name_plural': 'Property Types'},
        ),
        migrations.AddField(
            model_name='district',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.Country'),
            preserve_default=False,
        ),
    ]
