# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20181107_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyamenity',
            name='amenity',
        ),
        migrations.RemoveField(
            model_name='propertyamenity',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(to='cms.AmenityType'),
        ),
        migrations.DeleteModel(
            name='PropertyAmenity',
        ),
    ]
