# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_property_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='photo',
            field=models.ImageField(default="", upload_to=b''),
            preserve_default=False,
        ),
    ]
