# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_property_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
