# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_property_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LEASE', 'LEASE'), ('MONTHLY', 'MONTHLY'), ('QUATERLY', 'QUATERLY'), ('ANNUAL', 'ANNUAL'), ('OTHER', 'OTHER')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.PaymentType'),
        ),
    ]
